### ISSUE TITLE
[Discussion]: Swiper module

### ISSUE THREAD

**Issue by mtliendo** [GeeDollaHolla/canari-swipe#3]
Is Swiper related to [this module](https://github.com/nolimits4web/swiper) by chance?

**Comment by GeeDollaHolla** [comment]
It's accomplishing the same goal yes, but Swiper uses direct DOM manipulation because it's designed to drop into traditional static pages.. I think jQuery mobile has a similar implementation.

In my initial investigation a few months ago, I didn't find a suitable lib for what I was wanting. [This React wrapper](https://www.npmjs.com/package/react-dynamic-swiper) for Swiper could be an alternate route for our project, but I'm trying to keep the component as performant as possible with no direct DOM touches.

That said, it's not my intention for canari-swipe to provide the full functionality of Swiper and other existing mature libs.. mainly focusing on performance in React.
